version: 2
jobs:
  build-release:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/marketplace
    steps:
      - checkout
      - type: shell
        name: Install System Dependencies
        command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "webapp/package.json" }}
          - v1-dependencies-
      - run: cd webapp && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "webapp/package.json" }}
      - run:
          name: Build
          command: cd webapp && npm run build
          environment:
            NODE_PATH: src/
            NODE_ENV: production
            REACT_APP_API_URL: https://api.land.decentraland.org
            REACT_APP_VERSION: 0.1
            REACT_APP_ROLLBAR_ACCESS_TOKEN: ad890a7699424114a771373ee60720ac
            REACT_APP_INTERCOM_APP_ID: z0h94kay
            REACT_APP_MANA_TOKEN_CONTRACT_ADDRESS: 0x0f5d2fb29fb7d3cfee444a200298f468908cc942
            REACT_APP_LAND_REGISTRY_CONTRACT_ADDRESS: 0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d
      - save_cache:
          paths:
            - webapp/build
          key: build-release-{{ .Revision }}
  build-staging:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/marketplace
    steps:
      - checkout
      - type: shell
        name: Install System Dependencies
        command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "webapp/package.json" }}
          - v1-dependencies-
      - run: cd webapp && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "webapp/package.json" }}
      - run:
          name: Build
          command: cd webapp && npm run build
          environment:
            NODE_PATH: src/
            NODE_ENV: production
            REACT_APP_API_URL: https://api.land.decentraland.today
            REACT_APP_VERSION: 0.1
            REACT_APP_ROLLBAR_ACCESS_TOKEN: ad890a7699424114a771373ee60720ac
            REACT_APP_INTERCOM_APP_ID: z0h94kay
            REACT_APP_MANA_TOKEN_CONTRACT_ADDRESS: 0x2a8fd99c19271f4f04b1b7b9c4f7cf264b626edb
            REACT_APP_LAND_REGISTRY_CONTRACT_ADDRESS: 0x7a73483784ab79257bb11b96fd62a2c3ae4fb75b
      - save_cache:
          paths:
            - webapp/build
          key: build-staging-{{ .Revision }}
  deploy-release:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/marketplace
    steps:
      - restore_cache:
          keys:
          - build-release-{{ .Revision }}
      - run: sudo apt-get -y -qq install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is release
          command: aws s3 sync webapp/build s3://land.decentraland.org/ --delete --acl public-read
      - run:
          name: Invalidate Cloudfront cache
          command: aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id E2IF2EGXYQC4IG  --paths "/" "/*"
  deploy-staging:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/marketplace
    steps:
      - restore_cache:
          keys:
          - build-staging-{{ .Revision }}
      - run: sudo apt-get -y -qq install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is staging
          command: aws s3 sync webapp/build s3://land.decentraland.today/ --delete --acl public-read
      - run:
          name: Invalidate Cloudfront cache
          command: aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id E2X6577Q2KUDV8  --paths "/" "/*"

workflows:
  version: 2
  build-deploy-release:
    jobs:
      - build-release
      - deploy:
          requires:
            - build-release
          filters:
            branches:
              only: release

  build-deploy-staging:
    jobs:
      - build-staging
      - deploy:
          requires:
            - build-staging
          filters:
            branches:
              only: staging
